@php
    $title = 'Platform Overview Report · Property Basket';
    $docMeta = '<strong>PLATFORM OVERVIEW</strong><br>' . now()->format('d M Y · H:i');

    $fmtMoney = function ($n) {
        if ($n >= 1_000_000) return 'R ' . number_format($n / 1_000_000, 1) . 'm';
        if ($n >= 1_000)     return 'R ' . number_format($n / 1_000, 0) . 'k';
        return 'R ' . number_format($n, 0, '.', ',');
    };

    $fmtNum = fn ($n) => number_format($n, 0, '.', ',');

    $roleLabel = [
        'super_admin'  => 'Super Admin',
        'agency_admin' => 'Agency Admin',
        'agent'        => 'Agent',
        'landlord'     => 'Landlord',
        'tenant'       => 'Tenant',
        'contractor'   => 'Contractor',
    ];
@endphp

<x-pdf-layout :title="$title" :docMeta="$docMeta">

<h1>Platform Overview</h1>
<p class="subtitle">
    Snapshot as of {{ now()->format('l, d F Y') }} — generated by {{ $generatedBy }}
</p>

{{-- ─────────────────────────── KPIs ─────────────────────────── --}}
<h2>Key indicators</h2>
<table class="grid-2">
    <tr>
        <td class="left">
            <table class="kv">
                <tr>
                    <th>Monthly recurring revenue</th>
                    <td><strong style="font-size: 14px">{{ $fmtMoney($kpis['mrr']) }}</strong></td>
                </tr>
                <tr>
                    <th>GMV processed (YTD)</th>
                    <td><strong>{{ $fmtMoney($kpis['gmv_ytd']) }}</strong>
                        <div class="muted small">Rent + commissions year-to-date</div>
                    </td>
                </tr>
                <tr>
                    <th>Business accounts</th>
                    <td><strong>{{ $fmtNum($kpis['agency_accounts']) }}</strong>
                        <div class="muted small">{{ $kpis['agencies'] }} agencies · {{ $kpis['landlords'] }} landlords · {{ $kpis['contractors'] }} contractors</div>
                    </td>
                </tr>
            </table>
        </td>
        <td class="right">
            <table class="kv">
                <tr>
                    <th>End users</th>
                    <td><strong>{{ $fmtNum($kpis['end_users']) }}</strong>
                        <div class="muted small">{{ $kpis['agents'] }} agents + {{ $kpis['tenants'] }} tenants</div>
                    </td>
                </tr>
                <tr>
                    <th>Listings</th>
                    <td><strong>{{ $fmtNum($kpis['listings']) }}</strong></td>
                </tr>
                <tr>
                    <th>New signups this month</th>
                    <td><strong>+{{ $fmtNum($kpis['new_this_month']) }}</strong></td>
                </tr>
            </table>
        </td>
    </tr>
</table>

{{-- ─────────────────────────── Growth ─────────────────────────── --}}
<h2>Platform growth — last 6 months</h2>
<table class="lines">
    <thead>
        <tr>
            <th>Month</th>
            <th class="right">Agencies</th>
            <th class="right">Landlords</th>
            <th class="right">Contractors</th>
            <th class="right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($growth as $g)
            @php $rowTotal = $g['agencies'] + $g['landlords'] + $g['contractors']; @endphp
            <tr>
                <td><strong>{{ $g['label'] }}</strong></td>
                <td class="right mono">{{ $fmtNum($g['agencies']) }}</td>
                <td class="right mono">{{ $fmtNum($g['landlords']) }}</td>
                <td class="right mono">{{ $fmtNum($g['contractors']) }}</td>
                <td class="right mono bold">{{ $fmtNum($rowTotal) }}</td>
            </tr>
        @endforeach
    </tbody>
    <tfoot>
        <tr>
            <td>Totals</td>
            <td class="right mono">{{ $fmtNum(collect($growth)->sum('agencies')) }}</td>
            <td class="right mono">{{ $fmtNum(collect($growth)->sum('landlords')) }}</td>
            <td class="right mono">{{ $fmtNum(collect($growth)->sum('contractors')) }}</td>
            <td class="right mono">{{ $fmtNum(collect($growth)->flatMap(fn ($r) => [$r['agencies'], $r['landlords'], $r['contractors']])->sum()) }}</td>
        </tr>
    </tfoot>
</table>

{{-- ─────────────────────────── Recent signups ─────────────────────────── --}}
<h2>Recent signups</h2>
@if (count($recent_signups) === 0)
    <p class="muted">No signups yet.</p>
@else
    <table class="lines">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Joined</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($recent_signups as $s)
                <tr>
                    <td><strong>{{ $s['name'] }}</strong></td>
                    <td class="small mono">{{ $s['email'] }}</td>
                    <td>{{ $s['role_label'] }}</td>
                    <td class="small muted">{{ $s['created_at'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endif

{{-- ─────────────────────────── System health ─────────────────────────── --}}
<h2>System health</h2>
<table class="lines">
    <thead>
        <tr>
            <th>Component</th>
            <th>Status</th>
            <th>Detail</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($health as $h)
            @php
                $badge = match ($h['status']) {
                    'healthy' => 'badge-success',
                    'warning' => 'badge-warning',
                    default   => 'badge-danger',
                };
            @endphp
            <tr>
                <td><strong>{{ $h['name'] }}</strong></td>
                <td><span class="badge {{ $badge }}">{{ strtoupper($h['status']) }}</span></td>
                <td class="small muted">{{ $h['detail'] }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

</x-pdf-layout>
