@php
    $title = "Receipt {$payment->id} · Property Basket";
    $docMeta = '<strong>RECEIPT</strong><br>RCP-' . str_pad($payment->id, 6, '0', STR_PAD_LEFT);
@endphp

<x-pdf-layout :title="$title" :docMeta="$docMeta">

<h1>Rent Payment Receipt</h1>
<p class="subtitle">Confirmation of rent received via Property Basket trust account</p>

<table class="grid-2">
    <tr>
        <td class="left">
            <h3>Tenant</h3>
            <table class="kv">
                <tr><th>Name</th><td>{{ $tenant->name }}</td></tr>
                <tr><th>Email</th><td>{{ $tenant->email }}</td></tr>
            </table>
        </td>
        <td class="right">
            <h3>Property</h3>
            <table class="kv">
                <tr><th>Address</th><td>{{ $listing->address ?? $listing->title }}</td></tr>
                <tr><th>Suburb</th><td>{{ $listing->suburb }}, {{ $listing->city }}</td></tr>
                <tr><th>Lease #</th><td class="mono">{{ str_pad($lease->id, 6, '0', STR_PAD_LEFT) }}</td></tr>
            </table>
        </td>
    </tr>
</table>

<h2>Payment Details</h2>
<table class="kv">
    <tr><th>Period</th><td><strong>{{ \Carbon\Carbon::createFromFormat('Y-m', $payment->period_month)->format('F Y') }}</strong></td></tr>
    <tr><th>Due date</th><td>{{ $payment->due_date?->format('d M Y') ?? '—' }}</td></tr>
    <tr><th>Paid on</th><td>{{ $payment->paid_at?->format('d M Y \a\t H:i') ?? '—' }}</td></tr>
    <tr><th>Payment method</th><td>{{ str_replace('_', ' ', ucfirst($payment->payment_method ?? 'eft')) }}</td></tr>
    <tr><th>Paystack reference</th><td class="mono small">{{ $payment->paystack_reference ?? '—' }}</td></tr>
</table>

<div class="box" style="margin-top: 18px;">
    <table style="width: 100%;">
        <tr>
            <td style="font-size: 14px; font-weight: bold;">Amount paid</td>
            <td class="right mono" style="font-size: 18px; font-weight: bold;">R {{ number_format($payment->amount, 2) }}</td>
        </tr>
        <tr>
            <td colspan="2">
                <span class="badge badge-success">PAID · ON TIME</span>
                @if ($payment->paid_at && $payment->due_date && $payment->paid_at->gt($payment->due_date))
                    <span class="badge badge-warning">PAID LATE</span>
                @endif
            </td>
        </tr>
    </table>
</div>

<h2>Landlord / Agency</h2>
<table class="kv">
    @if ($agencyName)
        <tr><th>Managing agency</th><td>{{ $agencyName }}</td></tr>
    @endif
    @if ($landlordName)
        <tr><th>Property owner</th><td>{{ $landlordName }}</td></tr>
    @endif
    <tr><th>Agent</th><td>{{ $agentName ?? '—' }}</td></tr>
</table>

<div class="muted small" style="margin-top: 28px; padding-top: 12px; border-top: 1px solid #E5E7EB;">
    This receipt was auto-generated by Property Basket on behalf of the listing owner.
    Funds were processed through a Section 32 EAAB-compliant trust account.
    Disputes: contact the managing agency or email <a href="mailto:support@propertybasket.co.za">support@propertybasket.co.za</a> within 30 days.
</div>

</x-pdf-layout>
